<?php

/**
 * Implements hook_views_api().
 */
function sparql_views_test_views_api() {
  return array(
    'api' => '3.0',
  );
}

/**
 * Implements hook_rdf_mapping().
 */
function sparql_views_test_rdf_mapping() {
  $return = array(
    'sparql_views_test_person' =>array(
      'type' => 'sparql_views_resource',
      'bundle' => 'sparql_views_test_person',
      'mapping' => array(
        'rdftype' => array('foaf:Person'),
        'sparql_views_test_person_name' => array(
          'predicates' => array('foaf:name'),
        ),
      ),
    ),
  );

  return $return;
}